[project]
name = "service-on-click"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "saniatariq388", email = "saniatariq388@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.142.2",
    "sqlmodel>=0.0.47",
    "uvicorn[standard]>=0.54.0",
]

